apps/webapps/weather/signup/urls.py
from django.conf.urls import url

from . import views

app_name = 'signup'

urlpatterns = [
    url(r'^$', views.index, name='signup'),
    url(r'^confirm/$', views.confirm, name='confirm'),
]

apps/webapps/weather/weather/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^signup/', include('signup.urls')),
    url(r'^admin/', admin.site.urls),
]

apps/webapps/weather/signup/models.py
import os
import datetime
import pytz
import us # US state metadata
from datetime import datetime

from django.db import models
from django.db.utils import DatabaseError
from django.conf import settings

from .util import if_null

# means location was deleted from database
DEFAULT_LOCATION=999999


class BaseModel(models.Model):
	created_date = models.DateTimeField(auto_now_add=True)
	modified_date = models.DateTimeField(auto_now=True)

	class Meta:
		abstract = True

class Location(models.Model):
	city = models.CharField(max_length=255, null=True, blank=False)
	state = models.CharField(max_length=255, null=True, blank=False)

	@property
	def city_state(self):
		city_state_lst = [if_null(val,'NULL') for val in [self.id, self.city,self.state]]
		location_id, city, state = city_state_lst
		location_ret = tuple([location_id, city + ',' + state])
		return tuple(location_ret)

	@property
	def timezone(self):
		if (self.state is not None):
			timezone = us.states.lookup(self.state).time_zones[0]
		else:
			timezone = None
		return timezone

	@property
	def now(self):
		if (self.state is not None):
			timezone = us.states.lookup(self.state).time_zones[0]
			tz = pytz.timezone(timezone)
			now_time = datetime.now(tz)
		else:
			# later on override this with Central or Pacific time.
			now_time = datetime.now()
		return now_time

	def __str__(self):
		return "{}".format(self.city_state)

class Customer(models.Model):
	email = models.EmailField(null=False,blank=False,unique=True)
	location = models.ForeignKey(Location, on_delete=models.SET_DEFAULT, default=DEFAULT_LOCATION)

	def __str__(self):
		return "{} : {}".format(self.email,self.location.city + ',' + self.location.state)

apps/webapps/weather/signup/forms.py
import os

from django import forms

from .models import Customer, Location

DEFAULT_LOCATION=999999

def get_all_location_choices():
	query = Location.objects.exclude(id=DEFAULT_LOCATION).order_by('city','state')

	locations_lst = []

	for result in query:
		if result.id != '999999':
			locations_lst.append(result.city_state)

	locations_lst = tuple([loc for loc in locations_lst])

	return locations_lst


class CustomerForm(forms.Form):
	email = forms.EmailField(label='email',required=True,help_text="email address..")
	location = forms.ChoiceField(label='location',required=True, choices=get_all_location_choices(), help_text="location...")

apps/webapps/weather/signup/views.py
from django.shortcuts import render, render_to_response
from django.http import HttpResponseRedirect, HttpResponseBadRequest
from django.urls import reverse
from django.db import IntegrityError
from django.core.exceptions import ObjectDoesNotExist

from .models import Customer, Location
from .forms import CustomerForm
from .util import normalize_email

def index(request):
    if request.method == "POST":
        form = CustomerForm(request.POST)
        render_dict = {'form': form}
    else:
        form = CustomerForm()
        render_dict = {'form': form}

    if request.method == "POST":
        if form.is_valid():
            email = normalize_email(form.cleaned_data['email'])
            location = form.cleaned_data['location']
            try:
                customer_location = Location.objects.get(id = location)
                new_customer = Customer(email = email, location = customer_location)
                new_customer.save()
                return HttpResponseRedirect(reverse('signup:confirm'))
            except IntegrityError as e:
                render_dict['error'] = 'Email must be unique...'
                return render(request, 'signup/index.html', render_dict )
            except ObjectDoesNotExist as e: 
                render_dict['error'] = 'Location currently not available'
                return render(request, 'signup/index.html', render_dict )

        if not form.is_valid():
            return HttpResponseBadRequest("Validation Error")

    if ( request.method != "POST"):
        return render(request, 'signup/index.html',{'form': form})

def confirm(request):
    return render(request, 'signup/confirm.html')

apps/webapps/weather/weather/views.py
from django.shortcuts import render_to_response
from django.template import RequestContext

def handler400(request, *args, **argv):
    response = render_to_response('error/400.html', {},
                                  context_instance=RequestContext(request))
    response.status_code = 404
    return response

def handler404(request, *args, **argv):
    response = render_to_response('error/404.html', {},
                                  context_instance=RequestContext(request))
    response.status_code = 404
    return response

def handler500(request, *args, **argv):
    response = render_to_response('error/500.html', {},
                                  context_instance=RequestContext(request))
    response.status_code = 500
    return response

apps/webapps/weather/templates/signup/confirm.html
{% extends "templates/base.html" %}
{% load static %}

{% block title %} 
	<title> Thanks for Subscribing </title>
{% endblock %}

{% block content %}

<div class="container h-100">
    <div class="row h-100 justify-content-center align-items-center">
        <div class="card">
            <h4 class="card-header">Thanks for subscribing !!! </h4>
        </div>
        <div class="row">
            <div class="col-md-12">
                <a href="{% url 'signup:signup' %}"> <input class="btn btn-primary btn-lg btn-block" value="Return" name="Return"> </a>
            </div>
        </div>
    </div>
</div>

{% endblock %}

apps/webapps/weather/templates/signup/index.html
{% extends "templates/base.html" %}
{% load static %}

{% block title %} 
	<title> Weather Powered Email Signup </title>
{% endblock %}

{% block content %}

    <div class="container h-100">
        <div class="row h-100 justify-content-center align-items-center">
            <div class="card">
                <h4 class="card-header">Weather Powered Email</h4>
                <div class="card-body">
                    <form role="form" method="post" action="{% url 'signup:signup' %}">
                        {% csrf_token %}
                        <div class="row">
                            <div class="col-md-12">
                                <div class="form-group">
                                    {% if error %}
                                         <i> <p style="color: red;">
                                            {{ error }}
                                        </p> </i>
                                    {% endif %} 
                                    <label for="{{ form.email.id_for_label }}" >Email Address</label>
                                    <div class="input-group">
                                        <div class="input-group-prepend">
                                            <span class="input-group-text"><i class="fas fa-envelope" aria-hidden="true"></i></span> 
                                        </div>
                                        {{ form.email }}
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-12">
                                <div class="form-group">
                                    <label for="{{ form.location.id_for_label }}">Location</label>
                                    <div class="input-group">
                                        <div class="input-group-prepend">
                                            <span class="input-group-text"><i class="fas fa-mountain" aria-hidden="true"></i></span>
                                        </div>
                                        {{ form.location }}
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-12">
                                <input type="submit" class="btn btn-primary btn-lg btn-block" value="Subscribe" name="subscribe">
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>                  
                        
{% endblock %}

apps/webapps/weather/templates/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  {% block title %}<title>Weather Powered App</title>{% endblock %}
  <link rel="stylesheet" href="{% static 'vendor/css/bootstrap.min.css' %}" />
  <link rel="stylesheet" href="{% static 'css/custom.css' %}" type="text/css" />
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.3/css/all.css" integrity="sha384-UHRtZLI+pbxtHCWp1t77Bi1L4ZtiqrqD80Kn4Z8NTSRyMA2Fd33n5dQ8lWUE00s/" crossorigin="anonymous">
</head>
<body>
  {% block sidebar %}
  {% endblock %}
  {% block content %}{% endblock %}

  <script src="{% static 'vendor/js/bootstrap.min.js' %}" />
  <!-- <script src="{% static 'js/main.js' %}" /> --> 
  
</body>
</html>